spring:
  application:
    name: accounts
  profiles:
    active: production

# spring:
#  main:
#    allow-bean-definition-overriding: true
#  application:
#    name: accounts
#  profiles:
#    active: production
#  datasource:
#    url: jdbc:mysql://localhost:3306/userauth?serverTimezone=Europe/Warsaw&useSSL=False&allowPublicKeyRetrieval=true
#    username: root
#    password: PLSzW-2020
#  jpa:
#    hibernate:
#      ddl-auto: update
#  management:
#    endpoints:
#      web:
#        exposure:
#          include: '*'
#  info:
#    app:
#      name: "Accounts"
#      version: "0.0.1"
#      profile: production
#    serverInfo:
#      port: 7777
#application:
#  allow-get-accounts: true
