spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: accounts
  profiles:
    active: production
  datasource:
    url: ${accounts.datasource.url}
    username: ${accounts.datasource.username}
    password: ${accounts.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver     # org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${accounts.datasource.ddl-mode}
management:
  endpoints:
    web:
      exposure:
        include: '*'
info:
  app:
    name: "Customers"
    version: "0.0.1"
    profile: ${spring.profiles.active}
  serverInfo:
    port: ${server.port}
application:
  allow-get-customers: ${accounts.allow-get-customers}





#spring:
#  main:
#    allow-bean-definition-overriding: true
#  application:
#    name: accounts
#  profiles:
#    active: production
#  datasource:
#    url: ${accounts.datasource.url}
#    username: ${accounts.datasource.username}
#    password: ${accounts.datasource.password}
#    driver-class-name: com.mysql.cj.jdbc.Driver    #org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: ${accounts.datasource.ddl-mode}
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#info:
#  app:
#    name: "Accounts"
#    version: "0.0.1"
#    profile: ${spring.profiles.active}
#  serverInfo:
#    port: ${server.port}
#application:
#  allow-get-accounts: ${accounts.allow-get-accounts}